services:
  backend:
    container_name: backend
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./docker/backend/backend.Dockerfile
    image: ft_transcendence_be
    volumes:
      - ${PWD}:/workdir/
    networks:
      - network
    ports:
      - "8000"
    entrypoint: /workdir/docker/backend/entrypoint_be.sh
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ft_transcendence_users
      POSTGRES_USER: ft_transcendence_user
      POSTGRES_PASSWORD: ft_transcendence_password
    networks:
      - network
    ports:
      - "5432:5432"

  # nginx:
  #   container_name: nginx
  #   build:
  #     context: .
  #     dockerfile: docker/nginx/nginx.Dockerfile
  #   image: ft_transcendence_nginx
  #   entrypoint: /workdir/docker/nginx/nginx.sh
  #   volumes:
  #     - ${PWD}:/workdir/
  #   networks:
  #     - network
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped
  
  redis:
    image: 'redis:alpine'
    container_name: redis
    networks:
      - network
    ports:
      - "6380:6379"

  # for development
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: tstrassb@student.42wolfsburg.de
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - network
    ports:
      - 5050:80
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  network:
    driver: bridge