version: '3.8'

services:
  db:
    image: postgres:14.5
    container_name: postgres_db
    environment:
      POSTGRES_DB: ft_transcendence
      POSTGRES_USER: tstrassb
      POSTGRES_PASSWORD: _motheR22
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: