# Generated by Django 5.0.2 on 2024-02-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='DLRLWMZHXLBKL5DGQN3Y5SLP4S6H34QE', max_length=100),
        ),
    ]
