# Generated by Django 5.0.2 on 2024-02-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='VJPJ5NC7ASMUMUPOPSCF2ICLQNZWEGYS', max_length=100),
        ),
    ]
