# Generated by Django 5.0.2 on 2024-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0002_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='ZN7XBATPLAKR4WKQZ5OWOTI4A5QX6TYU', max_length=100),
        ),
    ]
