# Generated by Django 5.0.2 on 2024-02-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0003_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='OCT6IY3SV42BEBV7BI4L7FW67NMBCITI', max_length=100),
        ),
    ]
