# Generated by Django 5.0.2 on 2024-02-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0006_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='I4BT4BEZ7TI7EIQSG4ZXCCUIF42H4CP2', max_length=100),
        ),
    ]
