# Generated by Django 5.0.2 on 2024-02-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0007_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='543EYV63F2EB5SKTCNBOQFXDHWBG5CUE', max_length=100),
        ),
    ]
