# Generated by Django 5.0.2 on 2024-02-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0007_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='DLVMLTDZGVLS4I5TRNPV7WMSSS7I7SYQ', max_length=100),
        ),
    ]
