# Generated by Django 5.0.2 on 2024-02-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0008_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='FFGCNF7B72EYACZ4VD4OS62ENGYN3X6B', max_length=100),
        ),
    ]
