# Generated by Django 5.0.2 on 2024-02-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0008_alter_matchhistory_player2_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='P43Z36CY5KSJFNCXJOOLUOYDU3ZJASYL', max_length=100),
        ),
    ]
