# Generated by Django 5.0.2 on 2024-02-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0009_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='SNA63DRGK5ZKIJIF7OPLTPWT4Q4BQSHZ', max_length=100),
        ),
    ]
