# Generated by Django 5.0.2 on 2024-02-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0010_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='ESJ4H5TXIB3BQ4GN4XAC37TTPR4I7UHV', max_length=100),
        ),
    ]
