# Generated by Django 5.0.2 on 2024-02-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0011_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='ZM2L6HXYHRVXXRRZZ2FLG4ZJ5EDYK6IT', max_length=100),
        ),
    ]
