# Generated by Django 5.0.2 on 2024-02-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0011_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='KB7QDUQ3LOXW773LBSMBTUDR6Y6WZPB3', max_length=100),
        ),
    ]
