# Generated by Django 5.0.2 on 2024-02-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0011_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='NUA5XCMGPRDK5PGL25MFM3HRX67PQC4O', max_length=100),
        ),
    ]
