# Generated by Django 5.0.2 on 2024-02-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0012_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='VRPIUVI24WWIJCI6JMD3NTX6VHTZQLZG', max_length=100),
        ),
    ]
