# Generated by Django 5.0.2 on 2024-02-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0013_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='ONSJUVXKWBZKRBZSJ2ILQOUUS36O7LDG', max_length=100),
        ),
    ]
