# Generated by Django 5.0.2 on 2024-02-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0014_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='Y7ZLHE4ASW2QEEWJRJS2XD772QXJIFOR', max_length=100),
        ),
    ]
