# Generated by Django 5.0.2 on 2024-02-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0015_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='X7LCS7D2RB2JYJAAJD7SLDFNXFKCGI6Z', max_length=100),
        ),
    ]
