# Generated by Django 5.0.2 on 2024-02-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0016_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='HGF7YUQ673UT2A6MXMY5QHDEMAYZ2SA6', max_length=100),
        ),
    ]
