# Generated by Django 5.0.2 on 2024-02-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0018_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='QJ2LZJOCG3YKVI5D4HKTCT427CFOA2GL', max_length=100),
        ),
    ]
