# Generated by Django 5.0.2 on 2024-02-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0019_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='TWCY77MYIHB4DMBLMA6PETJVJPUBUPCF', max_length=100),
        ),
    ]
