# Generated by Django 5.0.2 on 2024-02-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0020_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='YN3BTQ446ETMQUY6M3WYBMHYJOSVHHZL', max_length=100),
        ),
    ]
